### ISSUE TITLE
How about captcha

### ISSUE THREAD

**Issue by qadir-genetech** [bkvirendra/didyoumean#1]
As this script is using the google search feature. I want this in my chat bot, where user chat with bot and make many typos and spelling mistake. I have to pass every single sentence in it. after many searches there is chance when google detects something fishy is going on. google will throw the captcha to detect whats going on.

**Comment by qadir-genetech** [comment]
Also this script is taking too long to respond.

**Comment by hartator** [comment]
You can use our service SerpApi to avoid CAPTCHAs. We support "Did you mean?" extraction natively: https://serpapi.com/spell-check
